
version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build: ./app
    container_name: app
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && python main.py"

volumes:
  pgdata:
  mongodbdata:
